### ISSUE TITLE
Jinja2 > 2.9  is known to be incompatible with ansible 2.2.1 (latest)

### ISSUE THREAD

**Issue by yabhinav** [yabhinav/docker-ansible-images#1]
With ANsible 2.2.1 release Jinj2 is hardcoded to be less than 2.9 due to certain bug in 2.9.[0-4] versions, Refer https://github.com/ansible/ansible/issues/21782

But this issue fixed with 2.9.5 and hence will need to install 2.8.1 version as the is causing issues since its locked for this ansible version

```
source ~/.bashrc; workon ansible_latest; ansible-playbook /etc/ansible/roles/role_under_test/playbooks/test.yml -vvv
/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Using /etc/ansible/ansible.cfg as config file
statically included: /etc/ansible/roles/role_under_test/tasks/ntp_setup.yml
ERROR! Unexpected Exception: The 'jinja2<2.9' distribution was not found and is required by ansible
the full traceback was:

Traceback (most recent call last):
  File "/root/.virtualenvs/ansible_latest/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/executor/task_queue_manager.py", line 177, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 394, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/plugins/callback/hipchat.py", line 32, in <module>
    from ansible.module_utils.urls import open_url
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/ansible/module_utils/urls.py", line 150, in <module>
    from urllib3.contrib.pyopenssl import ssl_wrap_socket
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/.virtualenvs/ansible_latest/lib/python2.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'jinja2<2.9' distribution was not found and is required by ansible

```

So as a workaround all the images have the ansible_latest installed  with 2.8.1

**Comment by yabhinav** [comment]
this only effects images with default python version 2.6.x

- CentOS 
    * 6: yabhinav/ansible:centos6     Install Jinja2==2.8.1
- Ubuntu
    * 12.04: yabhinav/ansible:ubuntu12.04        Install Jinja2==2.2
    * 14.04: yabhinav/ansible:ubuntu14.04        Install Jinja2==2.8.1
- Debian
    * 7: yabhinav/ansible:debian7      Install Jinja2==2.8.1
